site_name: Runeterra Setting TTRPG
site_url: https://SilksongHypeboi.github.io/runeterra
theme:
  name: material

plugins:
  - pub-obsidian:
    obsidian_dir: .obsidian
    links:
      wikilinks_enabled: true
      img_lazy: true